version: 1.0.{build}
image: Visual Studio 2017
clone_folder: c:\projects
install:
  - cd c:\projects
  - git submodule update --init --recursive
build_script:
- cmd: >-
    nuget restore c:\projects\tiled_resources\build\build.sln

    msbuild c:\projects\tiled_resources\build\build.sln /p:Configuration="Release" /verbosity:quiet
