version: 1.0.{build}
image: Visual Studio 2019 Preview
clone_folder: c:\projects
install:
  - cd c:\projects
  - git submodule update --init --recursive
build_script:
- cmd: >-
    nuget restore c:\projects\hello_directx_11\build.sln

    nuget restore c:\projects\hello_directx_12\build.sln

    msbuild c:\projects\hello_directx_11\build.sln /p:Configuration="Release" /verbosity:quiet
    
    msbuild c:\projects\hello_directx_12\build.sln /p:Configuration="Release" /verbosity:quiet
